spring.application.name=BoxStudio


spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://pg-19a965bf-tuba-c4.c.aivencloud.com:27118/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_unJcArhb_2KuXSk2Lvv
spring.datasource.driver-class-name=org.postgresql.Driver


# Wichtig für PostgreSQL: Erzwingt die korrekte SQL-Ausgabe
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



